### ISSUE TITLE
Error while using fs.copyTpl method

### ISSUE THREAD

**Issue by mohitsaini2114** [SBoudrias/mem-fs-editor#144]
I just want to take advantage of copyTpl method. I have the template file and data and I want to use EJS and want to generate a new file on destination folder. I'm doing this in normal .js class. I want to do this without running YO command. 

module.exports = class extends Generator {
  writing() {
    console.log("im suceessdeddd");
    this.fs.copyTpl(
      this.templatePath('index.html'),
      this.destinationPath('public/index.html'),
      { title: 'Templating with Yeoman' }
    );
  }
};

**But when I'm calling above class from my yargs.js class it's giving me below error-** 

M50336MSAINI2:app msaini2$ **node yargs.js**
/Users/msaini2/Documents/Premier/generator-cnab/node_modules/yeoman-generator/lib/index.js:423
      if (option.name in this._initOptions) {
                      ^

TypeError: Cannot use 'in' operator to search for 'help' in undefined
    at /Users/msaini2/Documents/Premier/generator-cnab/node_modules/yeoman-generator/lib/index.js:423:23
    at /Users/msaini2/Documents/Premier/generator-cnab/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/Users/msaini2/Documents/Premier/generator-cnab/node_modules/lodash/lodash.js:2990:24)
    at /Users/msaini2/Documents/Premier/generator-cnab/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/Users/msaini2/Documents/Premier/generator-cnab/node_modules/lodash/lodash.js:9342:14)
    at formatData.parseOptions (/Users/msaini2/Documents/Premier/generator-cnab/node_modules/yeoman-generator/lib/index.js:407:7)
    at formatData.option (/Users/msaini2/Documents/Premier/generator-cnab/node_modules/yeoman-generator/lib/index.js:352:10)
    at new Generator (/Users/msaini2/Documents/Premier/generator-cnab/node_modules/yeoman-generator/lib/index.js:97:10)
    at new formatData (/Users/msaini2/Documents/Premier/generator-cnab/generators/app/yargs.js:115:1)
    at Object.<anonymous> (/Users/msaini2/Documents/Premier/generator-cnab/generators/app/yargs.js:130:18)

**Comment by SBoudrias** [comment]
Hi, this seems to be coming from Yeoman itself; see the trace `yeoman-generator/lib/index.js:423`

I'll close this ticket.
