### ISSUE TITLE
<%% in copyTpl

### ISSUE THREAD

**Issue by kreja** [SBoudrias/mem-fs-editor#46]
In ejs, `<%%` Outputs a literal '<%', but it doesn't work for me in copyTpl, while making a yeoman generator.

I wrote this in my html file:

```html
<div id="nodata">
    <i class="iconfont icon-nodata"></i>
    <div><%%=(errCode!=0) ? errMsg : 'No data.' %></div>
</div>
```

It should be rendered as:

```
<div id="nodata">
    <i class="iconfont icon-nodata"></i>
    <div><%=(errCode!=0) ? errMsg : 'No data.' %></div>
</div>
```

However, I get:

```
SyntaxError: Unexpected token %
    at Function (native)
    at /Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/lodash/index.js:10809:16
    at /Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/lodash/index.js:11082:21
    at /Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/lodash/index.js:8152:31
    at Function.template (/Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/lodash/index.js:10808:20)
    at copy.process (/Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:11:16)
    at applyProcessingFunc (/Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:12:16)
    at EditionInterface.exports._copySingle (/Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:55:24)
    at EditionInterface.exports.copy (/Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/kelly/codespace/works/generator-k-midway/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
```

It seems that it can't recognize `<%%`

**Comment by SBoudrias** [comment]
Update to the latest yeoman-generator.
